"""add application_tracks table

Revision ID: 1f9dab03cc1e
Revises: 7e5e2e0f82a3
Create Date: 2026-06-15 17:27:34.283623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9dab03cc1e'
down_revision: Union[str, Sequence[str], None] = '7e5e2e0f82a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('bookmarked', 'applied', 'interviewing', 'rejected', 'offer', name='applicationstatus'), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_index(op.f('ix_application_tracks_status'), 'application_tracks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_tracks_status'), table_name='application_tracks')
    op.drop_table('application_tracks')
    # ### end Alembic commands ###
