"""Add NotificationSettings and vector index

Revision ID: 68ff4a0f29fc
Revises: 91728d1fd3a8
Create Date: 2026-06-16 12:57:47.358421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ff4a0f29fc'
down_revision: Union[str, Sequence[str], None] = '91728d1fd3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('scrape_interval_hours', sa.Integer(), nullable=True),
    sa.Column('min_score_threshold', sa.Integer(), nullable=True),
    sa.Column('slack_webhook', sa.String(length=1024), nullable=True),
    sa.Column('telegram_webhook', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('scrape_query', sa.String(length=255), nullable=True),
    sa.Column('scrape_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True)
    op.create_index('ix_job_listings_embedding', 'job_listings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_listings_embedding', table_name='job_listings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
