"""Initial Schema

Revision ID: 7e5e2e0f82a3
Revises: 
Create Date: 2026-06-09 12:07:03.366146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7e5e2e0f82a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('job_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.String(length=1024), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listings_external_id'), 'job_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_job_listings_source'), 'job_listings', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('skills_required', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills_nice', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('match_threshold', sa.Integer(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('skill_gaps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('salary_fit', sa.Boolean(), nullable=True),
    sa.Column('location_fit', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_scores')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_listings_source'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_external_id'), table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
