"""Fix unique constraint on application track

Revision ID: 91728d1fd3a8
Revises: 36cca6f0a8f1
Create Date: 2026-06-16 12:42:46.597975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91728d1fd3a8'
down_revision: Union[str, Sequence[str], None] = '36cca6f0a8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('application_tracks_listing_id_key'), 'application_tracks', type_='unique')
    op.create_unique_constraint('uq_user_listing', 'application_tracks', ['user_id', 'listing_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_listing', 'application_tracks', type_='unique')
    op.create_unique_constraint(op.f('application_tracks_listing_id_key'), 'application_tracks', ['listing_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
