"""use object_key instead of file_data

Revision ID: d82150a871ad
Revises: 68ff4a0f29fc
Create Date: 2026-06-18 00:02:29.792985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd82150a871ad'
down_revision: Union[str, Sequence[str], None] = '68ff4a0f29fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('application_tracks_listing_id_fkey'), 'application_tracks', type_='foreignkey')
    op.drop_constraint(op.f('application_tracks_user_id_fkey'), 'application_tracks', type_='foreignkey')
    op.create_foreign_key(None, 'application_tracks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_tracks', 'job_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_user_listing_score', 'job_scores', ['user_id', 'listing_id'])
    op.drop_constraint(op.f('job_scores_user_id_fkey'), 'job_scores', type_='foreignkey')
    op.drop_constraint(op.f('job_scores_listing_id_fkey'), 'job_scores', type_='foreignkey')
    op.create_foreign_key(None, 'job_scores', 'job_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_documents', sa.Column('object_key', sa.String(length=1024), nullable=False))
    op.drop_column('user_documents', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('user_documents', 'object_key')
    op.drop_constraint(None, 'job_scores', type_='foreignkey')
    op.drop_constraint(None, 'job_scores', type_='foreignkey')
    op.create_foreign_key(op.f('job_scores_listing_id_fkey'), 'job_scores', 'job_listings', ['listing_id'], ['id'])
    op.create_foreign_key(op.f('job_scores_user_id_fkey'), 'job_scores', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_listing_score', 'job_scores', type_='unique')
    op.drop_constraint(None, 'application_tracks', type_='foreignkey')
    op.drop_constraint(None, 'application_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('application_tracks_user_id_fkey'), 'application_tracks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('application_tracks_listing_id_fkey'), 'application_tracks', 'job_listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###
