"""add auto apply fields

Revision ID: d91a819e42b3
Revises: 05c0fc360ec9
Create Date: 2026-06-24 23:57:56.191349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91a819e42b3'
down_revision: Union[str, Sequence[str], None] = '05c0fc360ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('auto_apply_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('auto_apply_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'auto_apply_threshold')
    op.drop_column('notification_settings', 'auto_apply_enabled')
    # ### end Alembic commands ###
