"""update job embedding vector size to 768

Revision ID: fb6029598050
Revises: d82150a871ad
Create Date: 2026-06-18 00:04:02.853236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6029598050'
down_revision: Union[str, Sequence[str], None] = 'd82150a871ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('salary_range', sa.String(length=255), nullable=True))
    op.add_column('job_listings', sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_listings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('job_listings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.drop_column('job_listings', 'scraped_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('job_listings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.drop_column('job_listings', 'created_at')
    op.drop_column('job_listings', 'posted_date')
    op.drop_column('job_listings', 'salary_range')
    # ### end Alembic commands ###
